### ISSUE TITLE
Add telemetry functions to the cs_tester class

### ISSUE THREAD

**Issue by DAlba-sudo** [Lynx-Robotics/LynxRobotics2020-2021#4]
## Things to do:
1. In the [updatedCS class](https://github.com/Lynx-Robotics/LynxRobotics2020-2021/blob/advanced-color-sensor/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/updatedCS.java) add a telemetry.addData() method that tells the user they can press the start button (do this as the last item in each of the constructors).
2. In the [cs_tester class](https://github.com/Lynx-Robotics/LynxRobotics2020-2021/blob/advanced-color-sensor/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/cs_tester.java) add a telemetry.addData() method that tells the user they can stop pressing the a button (do this as soon as  it exits the if statement on line 26).

**Comment by cora-t** [comment]
### Closed
I added telemetry data to the cs_tester class along with the appropriate comments. This was to solve issue #4.
```Java
//Tell the user that the program is ready to start and that they can press the start 
//Telemetry data is added that notifies the user amd the telemetry is refreshed to show changed
telemetry.addData(null, "Press the start button"); //Added for #4
telemetry.update();
```
